
#ifndef KINGSLANDING_ONLINEWHITEBOARD_SERVER_COMMON_H_
#define KINGSLANDING_ONLINEWHITEBOARD_SERVER_COMMON_H_

#undef FORBIDDEN_EVIL_CONSTRUCTORS
#define FORBIDDEN_EVIL_CONSTRUCTORS(TypeName) \
TypeName(const TypeName&); \
void operator=(const TypeName&)


#endif